apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: custom-deployment
    version: new-dep  
  name: custom-deployment
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: custom-deployment
      version: new-dep  
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: custom-deployment
    spec:
      containers:
      - image: docker.io/library/httpd
        imagePullPolicy: Always
        name: httpd
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
